### ISSUE TITLE
Download link not working 

### ISSUE THREAD

**Issue by nssivashankar** [xjunz/AutoTask#1]

**Comment by gopep9** [comment]
i can find and install this app in coolapk market, but the share url copy from coolapk show "出错了，你访问的页面不存在
"

**Comment by pockyneko** [comment]
Me too

**Comment by Zymjason** [comment]
Can't download it,please solve the problem,thank you

**Comment by xjunz** [comment]
Ok fixed, here is the latest download link: https://fir.xcxwo.com/tasker
@nssivashankar @gopep9 @Rnreck @Zymjason
