### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by hhuimie** [xjunz/AutoTask#2]
1. 单击通知栏可以直接创建任务, 或者提供几个按钮
2. 悬浮助手可以冻结当前窗口, 类似快照形式, 这样就可以慢慢选择调试, 特别是对于那些开屏广告
3. 依次点击, 按完a, 然后延迟多少ms再点击b, 不确定有没有这个功能
谢谢您的开发

**Comment by xjunz** [comment]
你好，你说的1功能感谢反馈。2功能是有的，而且默认开启，在悬浮助手中叫做【固定屏幕截图】。3功能也是有的，可能需要您自行摸索一下。
